#!/bin/sh -e

# Script to create header files and links to configure
# U-Boot for a specific board.
#
# Parameters:  Target  Architecture  CPU  Board [VENDOR] [SOC]
#
# (C) 2002 DENX Software Engineering, Wolfgang Denk <wd@denx.de>
#

#./mkconfig -a ap121 mips mips ap121 ar7240 ar7240

#不是附加文档之后，而是重新生成
APPEND=no	# Default: Create new config file

# $# 这个程式的参数个数
# -gt 大于
# $0 这个程式的执行名字
# $n 这个程式的第n个参数值，n=1..9
# 将文档变为追加方式
# shift  左移一个参数，将参数位置整体左移一个位置
while [ $# -gt 0 ] ; do
	case "$1" in
	--) shift ; break ;;
	-a) shift ; APPEND=yes ;;
	*)  break ;;
	esac
done

#./mkconfig ap121 mips mips ap121 ar7240 ar7240

#参数个数小于4退出
#参数个数大于6退出
[ $# -lt 4 ] && exit 1
[ $# -gt 6 ] && exit 1

cd ./include

#
# Create link to architecture specific headers
# $2 = mips
rm -f asm
ln -s asm-$2 asm
rm -f asm-$2/arch

# $6 = ar7240
# $3 = mips
#-z string 如果 string 长度为零，则为真[ -z $myvar ]
#-o 当由pathname指定的文件或目录存在并且被子当前进程的有效用户ID所指定的用户拥有时返回真
if [ -z "$6" -o "$6" = "NULL" ] ; then
	ln -s arch-$3 asm-$2/arch
else
	ln -s arch-$6 asm-$2/arch
fi

if [ "$2" = "arm" ] ; then
	rm -f asm-$2/proc
	ln -s proc-armv asm-$2/proc
fi

#
# Create include file for Make
#
echo "ARCH   = $2" >  config.mk
echo "CPU    = $3" >> config.mk
echo "BOARD  = $4" >> config.mk

[ "$5" ] && [ "$5" != "NULL" ] && echo "VENDOR = $5" >> config.mk

[ "$6" ] && [ "$6" != "NULL" ] && echo "SOC    = $6" >> config.mk

#
# Create board specific header file
#
if [ "$APPEND" = "yes" ]	# Append to existing config file
then
	echo >> config.h
else
	> config.h		# Create new config file
fi
echo "/* Automatically generated - do not edit */" >>config.h
echo "#include <configs/$1.h>" >>config.h

exit 0
